/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探测 + 可见文档数
         * @description 根目录在运行期被删/不可读时返回 503 ``root_missing``（而不是谎报 ok）。
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 文档列表
         * @description 枚举可见 workdir 的概要：阶段状态、页数/段数/已译段数、最近活动时间。产物缺失的字段为 null（不是 0），坏产物不影响其它文档。
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /**
         * 上传 PDF（建 did）
         * @description multipart/form-data 上传源 PDF：校验 ``%PDF-`` 魔数与大小上限，在服务根目录下建 ``up-<slug>-<时间戳>`` 目录，把字节流式写进``<did>/source.pdf``（tmp + rename 原子落盘，不预建 agent/ 骨架）。did 由服务端生成（同名冲突递增 -2/-3），客户端给的文件名只贡献 slug。
         */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 文档元信息
         * @description 元信息 + 质量状态 + 编译状态。质量与编译**分开**报：quality.pipeline_ok 只有 check 门禁与 reviewer 都 pass 才为 true（编译成功不算质量通过）；compile 读 `.bdt-serve/compile.json`：status/revision/artifact 来自最近一次成功编译，stale = 当前草稿 revision 更大（旧 PDF 不得当成最新）。
         */
        get: operations["get_document_api_v1_documents__did__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/stage-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 7 阶段状态与真实耗时
         * @description 阶段名固定为 parse → translate → apply → build → check → review → report。起止时间优先取最新 run 的 manifest.json（token 为 manifest），manifest 缺该段时回退 run_state.json 的 at + duration_s（token 为 run_state，起点由完成时刻与实测耗时反推）。
         */
        get: operations["get_stage_state_api_v1_documents__did__stage_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/paragraphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 段落面板数据（原文/译文/排版 join）
         * @description 以段落 id 左连接 anchors / translated.jsonl / layout_geometry / parse 快照，数量不一致时缺侧为 null（不假设相等）。page 为 1 基 PDF 页码。
         */
        get: operations["get_paragraphs_api_v1_documents__did__paragraphs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * bbox 几何（parse 快照 / layout 几何）
         * @description kind=parse 读最新 run 的 parse 段落实体，box 是 pdf_topleft（y 向下）；kind=layout 读 layout_geometry.json，box 是 pdf_native（y 向上）并附 page_info 的 cropbox。两套坐标系统**不做转换**，由前端按 coord_system 换算。缺对应产物时返回 404（snapshot_unavailable / geometry_unavailable），不用空数组冒充成功。
         */
        get: operations["get_geometry_api_v1_documents__did__geometry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 结构审查 / 排版 lint / 链接审计
         * @description 三份检查产物原样透传（不裁剪字段），available 标志说明各自是否可用（旧 workdir 可能缺项）。
         */
        get: operations["get_check_api_v1_documents__did__check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 事件分页
         * @description 读 events.jsonl 的一页（默认最新 run，?run_id= 可指定）。next_after_seq 是**扫描位置**：即使 stage/kind 过滤后本页 0 条也会推进。文件尾部的半行不发布，损坏行跳过。没有任何 run 归档 → 404 events_unavailable。
         */
        get: operations["get_events_api_v1_documents__did__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 事件实时流（SSE）
         * @description text/event-stream：每条形如 `event: <kind>` / `id: <run_id>:<seq>` / `data: <事件 JSON>`；15s 无事件发一行 `: ping` 注释。断线续传用 Last-Event-ID（`<run_id>:<seq>`）或 `?after_seq=`；换 run 时必须带新的 ?run_id=。没有 run 归档 → 404 events_unavailable（错误走统一 JSON 信封，不是 SSE 帧）。
         */
        get: operations["stream_events_api_v1_documents__did__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 可下载产物清单
         * @description 白名单产物的清单（name/path/kind/size/mtime），name 就是下载 URL 的 {name}。白名单 = 根级 FINAL_REPORT.md(report) / source.pdf(source) + output/*.pdf(pdf) + agent/*.md(markdown) 与 agent/*.json|*.jsonl(json)；不递归子目录，debug/ 与 run 临时产物不在其中。没有任何产物时返回空数组（清单本身可用且确实为空，不是缺产物）。
         */
        get: operations["list_artifacts_api_v1_documents__did__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下载产物（支持 Range/HEAD）
         * @description 只允许清单内的白名单名字；越界（`..`/绝对路径/符号链接指向 workdir 外）与不在白名单内的名字都返回 404 ``artifact_not_found``，不泄露存在性。支持 `Range: bytes=a-b`（206 + Content-Range，pdf.js 依赖）与 HEAD。
         */
        get: operations["get_artifact_api_v1_documents__did__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 该文档的 job 列表
         * @description 该文档的全部 job，新 → 旧（job id 单调 ⇒ 倒序即时间倒序）；`?status=` 按状态过滤（取值同 job 的 status）。
         */
        get: operations["list_jobs_api_v1_documents__did__jobs_get"];
        put?: never;
        /**
         * 提交 job（run / check / compile）
         * @description 以子进程跑 `bdt run`（同文档串行：已有活动 job → 409 document_busy；全局最多 2 个并发，超出排队 queued）。202 的 status 恒为 queued，真实状态轮询 GET /jobs/{jid}。`compile`（W09）在隔离副本里跑apply+build 并原子发布 PDF：`scope=pages` 按已批准设计回退全量（记录 requested_scope/effective_scope/downgrade_reason），`base_revision` 与当前草稿不一致 → 409 revision_conflict。retranslate 未实现 → 422 action_not_available。客户端只能给action/from/pages/dual/profile/scope/base_revision：translator/reviewer/timeout 之类一律 422 forbidden_field。
         */
        post: operations["create_job_api_v1_documents__did__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * job 全状态
         * @description job 快照全字段（envelope 是子进程 stdout 收尾信封原文，最长 4KB）。status ∈ queued|running|succeeded|failed|canceled|interrupted；pid/pgid 只在 running 时有值。
         */
        get: operations["get_job_api_v1_jobs__jid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消 job（终止整个进程组）
         * @description 幂等：活动 job → 202，已终态 → 200 原样返回。running 时给整个进程组发SIGTERM（连带 translator 孙进程）→ 5s 宽限 → SIGKILL，进程真的退出后才置 canceled 并释放文档槽；queued 直接 canceled。不自动重跑。
         */
        post: operations["cancel_job_api_v1_jobs__jid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读草稿
         * @description 当前草稿：`revision`、`updated_at`、`paragraphs`（每段 `target`/`layout`/`updated_at`）。从没写过 → `revision=0` + 空 `paragraphs`（不是 404）。
         */
        get: operations["get_draft_api_v1_documents__did__draft_get"];
        put?: never;
        post?: never;
        /**
         * 清空草稿（revision 不回退）
         * @description 删掉全部段落覆盖；`revision` 继续 `+1`（**不回退**，前端靠单调 revision 判断 stale）。返回清空后的草稿，并触发防抖编译。活动 job 期间 → `409 document_busy`。
         */
        delete: operations["delete_draft_api_v1_documents__did__draft_delete"];
        options?: never;
        head?: never;
        /**
         * 写草稿（乐观并发 + 防抖编译）
         * @description `base_revision` 必须等于服务器当前 `revision`，否则 `409 revision_conflict`（`detail.current_revision`）。`paragraphs` 是`{段落 id: {target?, layout?}}`，`null` = 删字段、整段 `null` = 删该段。成功 `revision+1` 并触发 1.5s 防抖编译。活动 job 期间 → `409 document_busy`；字段/范围不合法 → `422 draft_invalid`。
         */
        patch: operations["patch_draft_api_v1_documents__did__draft_patch"];
        trace?: never;
    };
    "/api/v1/documents/{did}/paragraphs/{pid}/retranslate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 生成重译候选（不采用就不改译文）
         * @description 对不满意段落让 AI 重译：建一条 `pending` 候选并提交 `action=retranslate` job（同文档串行、全局限流、可取消——与其它 job 同规则）。翻译命令来自 `profile`（客户端永远不传命令），生成在**隔离副本**里跑，`agent/translated.md`／`draft.json`／`output/` 一概不动；候选译文只在人工采用后才会进草稿。`profile` 缺失／该 profile 没配 translator → 422 `profile_missing`；未知 profile → 422 `unknown_profile`；pid 不存在 → 404 `paragraph_not_found`；有活动 job → 409 `document_busy`。
         */
        post: operations["retranslate_api_v1_documents__did__paragraphs__pid__retranslate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/paragraphs/{pid}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 该段的候选列表
         * @description 该段的重译候选：最新的 `pending` 在前，其后是已决定的候选（新 → 旧）。`candidate_target=null` 表示还在生成中（job 结束前）；生成失败/取消的候选行会被删掉，不留在列表里。pid 不在段落产物里 → 404 `paragraph_not_found`。
         */
        get: operations["list_candidates_api_v1_documents__did__paragraphs__pid__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/paragraphs/{pid}/candidates/{cid}/adopt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 采用候选（写草稿 + 防抖编译）
         * @description 人工采用：把候选译文写成该段的草稿 `target`（走草稿通道，`revision+1`）并触发1.5s 防抖编译，然后把候选标成 `adopted`。返回**新草稿**（与 `PATCH /draft` 同一形状），前端可直接写进缓存。不需要 `base_revision`（服务端自己在写锁内取当前 revision）。已有相同译文覆盖 → 仍 +1（不猜用户意图）。cid 不存在 → 404 `candidate_not_found`；已采用/已拒绝 → 409 `candidate_decided`；还在生成中 → 409 `candidate_not_ready`；有活动 job（要写草稿）→ 409 `document_busy`。
         */
        post: operations["adopt_candidate_api_v1_documents__did__paragraphs__pid__candidates__cid__adopt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/paragraphs/{pid}/candidates/{cid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 拒绝候选（只改状态）
         * @description 把候选标成 `rejected`：不改译文、不改草稿、不触发编译（因此**不**受活动 job 的草稿只读守卫限制）。重复拒绝是幂等的（返回当前候选，不再改任何东西）；已采用的候选不能用拒绝改回去 → 409 `candidate_decided`；cid 不存在 → 404 `candidate_not_found`。
         */
        post: operations["reject_candidate_api_v1_documents__did__paragraphs__pid__candidates__cid__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 版本归档清单（新 → 旧）
         * @description 每次**成功**编译发布的产物自动归档成一个版本（`revision` = 当时捕获的草稿revision），保留最近 50 个（超出淘汰最旧的版本文件与清单行）。响应是清单的**新 → 旧**倒序 + 当前编译上下文：`current_revision`/`stale` 取自详情端点的`compile`（§3.2）—— 当前可下载的那一版恒是 `output/` 的最新发布，不是清单的最新行。`trigger` ∈ `debounce`（草稿保存后的服务端自动编译）/ `manual`（显式POST compile）；`quality` 是发布时刻的质量快照，**只记录不门禁**（`pipeline_ok=false` 的版本照样可下载）。从没编译成功过 → 空数组（不是 404）。
         */
        get: operations["list_versions_api_v1_documents__did__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/versions/{revision}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下载指定历史版本
         * @description 返回那一版的字节（`application/pdf`，`Content-Disposition: inline`，文件名 `<原产物名去 .pdf>.r<revision>.pdf`）。只认清单里有、且确实落在 `.bdt-serve/versions/` 下的数字名文件：非数字 / 不在清单 / 文件缺失 / 符号链接越界一律 404 `version_not_found`（同一个码，不泄露存在性）。当前版本仍走 `GET /artifacts`（`output/` 的最新发布）。
         */
        get: operations["download_version_api_v1_documents__did__versions__revision__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * profile 列表（只有 id/label）
         * @description 已知 profile id（``<store_base>/.bdt-serve/profiles.json`` ∪ ``BDT_PROFILE_<ID>_<FIELD>`` 环境变量），按 id 排序。**响应里没有命令字段**：translator/reviewer 命令只存在于服务端。``has_translator``/``has_reviewer`` 只说明配没配，不说明配的是什么。
         */
        get: operations["list_profiles_api_v1_profiles_get"];
        /**
         * 新建 / 更新 / 删除 profile（只接受脚本路径引用）
         * @description 局部更新一条 profile 并原子写回 profiles.json。``translator_script``/``reviewer_script`` 是**脚本路径引用**（``scripts/<name>``，必须落在 ``<store_base>/scripts/`` 或仓库 ``scripts/`` 内，符号链接越界拒绝），不是命令字符串：含 shell 元字符 → 422 ``forbidden_field``，白名单外/不存在 → 422 ``script_path_forbidden``。字段缺席 = 不动，显式 null = 删该字段，三个字段都空 = 删整个 profile。响应形状与 GET 的条目相同（无命令）。
         */
        put: operations["put_profile_api_v1_profiles_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全局词表（条目 + 条数）
         * @description 返回 ``<store_base>/.bdt-serve/glossary.csv`` 的内容，已按 ``source`` 排序、同 source 只留最后一条。没有词表 → ``entries=[]``/``count=0``（不是 404）。
         */
        get: operations["get_glossary_api_v1_glossary_get"];
        /**
         * 整表替换全局词表
         * @description 用 ``entries`` **整体替换**词表（本地编辑后一次保存，不做行级 patch）。校验：source/target 去空白后必须非空且在长度上限内、同 source 后者覆盖前者、按 source 排序；不合法 → 422 ``glossary_invalid``（带 ``index``/``field``）且**盘上一字不改**。空数组 = 清空（等效于 DELETE）。**词表变更不回溯**：已经翻译过的内容不会自动重译，重新跑翻译才生效。
         */
        put: operations["put_glossary_api_v1_glossary_put"];
        post?: never;
        /**
         * 清空全局词表（幂等）
         * @description 删掉词表文件。之后翻译 job 不再注入（``use_glossary=true`` 也一样），``GET`` 返回空表。已经翻译过的内容不受影响（词表变更不回溯）。
         */
        delete: operations["delete_glossary_api_v1_glossary_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactItem
         * @description ``GET /api/v1/documents/{did}/artifacts`` 的一件产物（api.md §1.5）。
         *
         *     ``name`` 既是稳定短名也是下载键（``artifacts/{name}`` 的路径参数）：workdir
         *     相对路径，如 ``output/paper.mono.pdf`` / ``agent/translated.md`` / ``source.pdf``。
         *     ``path`` 与 ``name`` 同值（沿用 W02 ``PdfOutput.path`` 的"相对 workdir"约定，
         *     不是服务端绝对路径）。
         *
         *     W03 没有草稿编译产物（草稿与编译修订号按 §3.2 在 W09 落地），所以 §1.5 提到的
         *     ``revision`` 字段在这里暂不出现 —— 没有真实来源就不塞假值。
         */
        ArtifactItem: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "markdown" | "json" | "report" | "source";
            /** Size */
            size: number;
            /** Mtime */
            mtime: string;
        };
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /**
             * File
             * @description multipart/form-data 的 file 字段：源 PDF（读前 5 字节必须是 %PDF-，上限 209715200 字节）。文件名只用来生成 did 的 slug。
             */
            file: string;
        };
        /**
         * CandidateItem
         * @description 一条重译候选（``<workdir>/.bdt-serve/candidates.json`` 的条目 / 各端点的响应体）。
         *
         *     **候选不是译文**：``candidate_target`` 在采用（adopt）之前不出现在任何产物里
         *     （不写 ``agent/translated.md``、不写草稿、不影响编译）。``source``/``baseline_target``
         *     是生成时刻的快照（原文用与 ``GET /paragraphs`` 同一口径的 canonical 文本；基线取
         *     ``translated.jsonl``），前端拿它们做三段对比。
         *
         *     ``candidate_target`` 为 ``null`` = 生成中（job 还没跑完）；生成失败/被取消的候选行
         *     会被删掉（不留在列表里骗人），所以这个态只在 job 活动期间可见。
         */
        CandidateItem: {
            /** Id */
            id: string;
            /** Pid */
            pid: string;
            /** Source */
            source?: string | null;
            /** Baseline Target */
            baseline_target?: string | null;
            /** Candidate Target */
            candidate_target?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "adopted" | "rejected";
            /** Model Label */
            model_label?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Created At */
            created_at: string;
            /** Adopted At */
            adopted_at?: string | null;
        };
        /**
         * CandidateJobAccepted
         * @description ``POST /documents/{did}/paragraphs/{pid}/retranslate`` 的 202 响应（api.md §3.6）。
         *
         *     ``status`` 恒为 ``queued``（契约形状，与 ``JobAccepted`` 同一口径）：真实状态轮询
         *     ``GET /jobs/{jid}``。候选行在提交时就建好了（``status=pending`` + ``candidate_target=null``），
         *     job 成功后填上候选译文、失败/取消时删掉。
         */
        CandidateJobAccepted: {
            /** Candidate Id */
            candidate_id: string;
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
            /**
             * Action
             * @default retranslate
             * @constant
             */
            action: "retranslate";
        };
        /**
         * CandidateListResponse
         * @description ``GET /documents/{did}/paragraphs/{pid}/candidates``：该段的候选列表。
         *
         *     ``items`` 里最新的 ``pending`` 在前（生成中的那个最先看到），其后是已决定的候选（新 → 旧）。
         */
        CandidateListResponse: {
            /** Pid */
            pid: string;
            /** Items */
            items: components["schemas"]["CandidateItem"][];
        };
        /**
         * CandidateRetranslateRequest
         * @description ``POST /documents/{did}/paragraphs/{pid}/retranslate`` 的请求体（api.md §3.6）。
         *
         *     只有一个字段：``profile``（provider **id**）。translator 命令由服务端从 profile 解析，
         *     客户端连字段都没有（带了会被 422 ``forbidden_field``）；``feedback`` 之类"给模型的自由
         *     文本"v1 不接受（提示词由服务端拼，见 §3.6）。
         */
        CandidateRetranslateRequest: {
            /**
             * Profile
             * @description provider profile id（候选生成只用它的 translator 命令）；必填（缺 → 422 profile_missing），未知 id → 422 unknown_profile，该 profile 没配 translator → 422 profile_missing
             */
            profile?: string | null;
        };
        /**
         * CheckAvailability
         * @description check 三源产物各自是否可用（旧 workdir 可能缺某项）。
         */
        CheckAvailability: {
            /** Review */
            review: boolean;
            /** Lint */
            lint: boolean;
            /** Link */
            link: boolean;
        };
        /**
         * CheckResponse
         * @description ``GET /api/v1/documents/{did}/check``：三源原样透传（不裁剪字段）。
         */
        CheckResponse: {
            /** Did */
            did: string;
            /** Review Verdict */
            review_verdict?: {
                [key: string]: unknown;
            } | null;
            /** Layout Lint */
            layout_lint?: {
                [key: string]: unknown;
            } | null;
            /** Link Audit */
            link_audit?: {
                [key: string]: unknown;
            } | null;
            available: components["schemas"]["CheckAvailability"];
        };
        /**
         * CompileStatus
         * @description ``compile``：服务端管理的草稿编译产物（api.md §3.2，W09 接真）。
         *
         *     真源是 ``<workdir>/.bdt-serve/compile.json``（由
         *     :mod:`babeldoc_tools.serve.compile` 写）：``revision``/``artifact`` 恒指
         *     **最近一次成功发布**的产物（下载链接靠它标修订），``status``/失败原因描述
         *     **最近一次尝试**，``stale = 当前草稿 revision > revision``（草稿一动，旧 PDF
         *     就不许再被当成最新）。没有 compile.json（从没编译过）→ ``none``/``0``/``null``。
         *     注意：``bdt run`` 直接产出的 PDF 不是编译修订，已放在 :attr:`DocumentDetail.pdf`。
         */
        CompileStatus: {
            /**
             * Status
             * @default none
             * @enum {string}
             */
            status: "none" | "running" | "ok" | "failed";
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Artifact */
            artifact?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DocumentAvailability
         * @description 哪些 workdir 产物可用（缺失或损坏 → false，对应字段为 null）。
         */
        DocumentAvailability: {
            /** Run State */
            run_state: boolean;
            /** Anchors */
            anchors: boolean;
            /** Translated */
            translated: boolean;
            /** Geometry */
            geometry: boolean;
            /** Parse Snapshot */
            parse_snapshot: boolean;
            /** Review Verdict */
            review_verdict: boolean;
            /** Layout Lint */
            layout_lint: boolean;
            /** Link Audit */
            link_audit: boolean;
        };
        /**
         * DocumentDetail
         * @description ``GET /api/v1/documents/{did}``：列表项字段 + 元信息。
         */
        DocumentDetail: {
            /** Did */
            did: string;
            /** Title */
            title?: string | null;
            /** Pages */
            pages?: number | null;
            /** Paragraph Count */
            paragraph_count?: number | null;
            /** Translated Count */
            translated_count?: number | null;
            /** Stage Summary */
            stage_summary: {
                [key: string]: string;
            };
            /** Updated At */
            updated_at?: string | null;
            pdf: components["schemas"]["DocumentPdf"];
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            quality: components["schemas"]["QualityStatus"];
            compile: components["schemas"]["CompileStatus"];
            available: components["schemas"]["DocumentAvailability"];
        };
        /**
         * DocumentListItem
         * @description 文档列表项 / 详情里的公共计数部分（``GET /api/v1/documents``）。
         *
         *     ``None`` = 对应产物缺失或损坏（不是 0）：缺 ``translated.jsonl`` 时
         *     ``translated_count`` 为 null，产物存在但没译文才是 0。
         */
        DocumentListItem: {
            /** Did */
            did: string;
            /** Title */
            title?: string | null;
            /** Pages */
            pages?: number | null;
            /** Paragraph Count */
            paragraph_count?: number | null;
            /** Translated Count */
            translated_count?: number | null;
            /** Stage Summary */
            stage_summary: {
                [key: string]: string;
            };
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DocumentPdf
         * @description 详情里的 PDF 来源与产物路径。
         */
        DocumentPdf: {
            /** Source */
            source?: string | null;
            /**
             * Outputs
             * @default []
             */
            outputs: components["schemas"]["PdfOutput"][];
        };
        /**
         * DocumentUploaded
         * @description ``POST /documents`` 的 201 响应（api.md §3.5 冻结形状）。
         *
         *     ``did`` 由服务端生成（``up-<slug>-<yyyymmdd-hhmmss>``，同名冲突递增后缀）；
         *     ``source`` 恒为 ``source.pdf`` —— 上传只落这一个文件（W03 产物白名单里的
         *     ``kind=source``），不建任何 ``agent/`` 骨架。
         */
        DocumentUploaded: {
            /** Did */
            did: string;
            /** Bytes */
            bytes: number;
            /**
             * Source
             * @default source.pdf
             * @constant
             */
            source: "source.pdf";
        };
        /**
         * DraftParagraph
         * @description 一段草稿：译文覆盖 + 排版覆盖（两者都可缺）。
         */
        DraftParagraph: {
            /** Target */
            target?: string | null;
            /** Layout */
            layout?: {
                [key: string]: unknown;
            } | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DraftPatchRequest
         * @description ``PATCH /documents/{did}/draft`` 的请求体（api.md §3.3）。
         *
         *     只有两个字段：``base_revision``（乐观并发）与 ``paragraphs``（``{段落 id: 补丁}``）。
         *     ``paragraphs`` 故意声明成宽松的 ``dict[str, Any]``：字段/范围的逐条校验在
         *     :func:`babeldoc_tools.serve.draft.validate_changes` 里做，错误码是稳定的
         *     ``422 draft_invalid`` + ``detail.errors``（不是 pydantic 的 ``validation_error``）。
         */
        DraftPatchRequest: {
            /**
             * Base Revision
             * @description 客户端期望的当前草稿 revision；与服务器不一致 → 409 revision_conflict
             */
            base_revision: number;
            /**
             * Paragraphs
             * @description {"段落 id": {"target"?: str|null, "layout"?: object|null}}，null = 删除；整段置 null = 删掉该段全部覆盖
             */
            paragraphs?: {
                [key: string]: unknown;
            };
        };
        /**
         * DraftResponse
         * @description ``GET/PATCH/DELETE /documents/{did}/draft`` 的响应体（api.md §3.3 冻结形状）。
         */
        DraftResponse: {
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Paragraphs
             * @default {}
             */
            paragraphs: {
                [key: string]: components["schemas"]["DraftParagraph"];
            };
        };
        /**
         * EventsPage
         * @description ``GET /api/v1/documents/{did}/events``：一页事件 + 续传游标（api.md §1.3）。
         *
         *     ``run_id`` 是本页事件**实际来源**的 run。``seq`` 只在单 run 内单调递增，游标语义
         *     是 ``(run_id, seq)``（api.md §1.3），前端要靠它组 SSE 的 ``Last-Event-ID``；
         *     这是对 §1.3 响应形状的 additive 扩展（三个原键不变）。
         *
         *     ``next_after_seq`` 是**扫描位置**而不是匹配位置：带 ``stage``/``kind`` 过滤时
         *     即使本页 0 条匹配也必须推进，否则过滤条件会卡住轮询。``events`` 是事件原样
         *     透传（``{seq, at, stage, kind, data}``，不裁剪 ``data``）。
         */
        EventsPage: {
            /** Run Id */
            run_id: string;
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Next After Seq */
            next_after_seq: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * GeometryResponse
         * @description ``GET /api/v1/documents/{did}/geometry``：bbox 数据。
         *
         *     ``kind=parse`` 用 ``run_id``/``entities``/``relations``（快照，``pdf_topleft``）；
         *     ``kind=layout`` 用 ``pages``/``paragraphs``/``page_info``（几何产物，``pdf_native``）。
         *     两类的 box 坐标系不同且**不做转换**，前端按 ``coord_system`` 自行换算。
         */
        GeometryResponse: {
            /** Did */
            did: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "parse" | "layout";
            /**
             * Coord System
             * @enum {string}
             */
            coord_system: "pdf_topleft" | "pdf_native";
            /** Page */
            page?: number | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Entities
             * @default []
             */
            entities: {
                [key: string]: unknown;
            }[];
            /**
             * Relations
             * @default []
             */
            relations: {
                [key: string]: unknown;
            }[];
            /** Pages */
            pages?: number | null;
            /**
             * Paragraphs
             * @default []
             */
            paragraphs: {
                [key: string]: unknown;
            }[];
            /**
             * Page Info
             * @default []
             */
            page_info: {
                [key: string]: unknown;
            }[];
        };
        /**
         * GlossaryEntryModel
         * @description 一条术语对 ``source → target``（``note`` 可选，给人看的备注，不参与匹配）。
         */
        GlossaryEntryModel: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Note */
            note?: string | null;
        };
        /**
         * GlossaryResponse
         * @description ``GET/PUT/DELETE /glossary`` 的响应：规范化后的条目 + 条数。
         *
         *     ``entries`` 按 ``source`` 排序、同一 source 只留最后一条（校验/去重/排序都在
         *     :func:`babeldoc_tools.glossary.normalize_entries`，与 CLI 注入时**同一份**规则）。
         *     没有词表 = 空数组（不是错误）。
         */
        GlossaryResponse: {
            /** Entries */
            entries: components["schemas"]["GlossaryEntryModel"][];
            /** Count */
            count: number;
        };
        /**
         * GlossaryUpdateRequest
         * @description ``PUT /glossary`` 的请求体：**整表替换**（``{entries: [...]}``）。
         *
         *     编辑器在本地编完整张表再一次性保存。服务端不收 CSV 文本：CSV 的解析/导出在前端，
         *     导入导出都走这个 JSON 形状。校验失败 → 422 ``glossary_invalid``（盘上一字不改）。
         */
        GlossaryUpdateRequest: {
            /** Entries */
            entries: components["schemas"]["GlossaryEntryModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/v1/health``：进程存活 + 当前可见文档数。
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Api
             * @default /api/v1
             */
            api: string;
            /** Version */
            version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "root" | "workdir";
            /** Root */
            root: string;
            /** Documents */
            documents: number;
        };
        /**
         * JobAccepted
         * @description ``POST /documents/{did}/jobs`` 的 202 响应（api.md §3.4 冻结形状）。
         *
         *     ``status`` 恒为 ``queued``（契约形状）：真正状态以 ``GET /jobs/{jid}`` 为准 ——
         *     有空槽位时 job 在响应发出前就已经 ``running`` 了。
         */
        JobAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
            /**
             * Action
             * @enum {string}
             */
            action: "run" | "check" | "compile";
        };
        /**
         * JobCreateRequest
         * @description ``POST /documents/{did}/jobs`` 的请求体（api.md §3.4）。
         *
         *     客户端只能给这些字段：``action``/``from``/``pages``/``dual``/``profile``
         *     （``compile`` 用 ``scope``/``base_revision``）；``profile`` 只接 **id**。
         *     translator/reviewer/timeout 之类命令与密钥字段一律由服务端从 profile 解析，
         *     带了就 422 ``forbidden_field``（见
         *     :data:`babeldoc_tools.serve.routers.jobs.FORBIDDEN_JOB_FIELDS`）—— 这些字段**不**
         *     出现在下面的模型里，避免被前端代码生成当成可用参数。
         *
         *     ``from`` 是 Python 关键字，用别名叫回来；OpenAPI 里仍是 ``from``。
         */
        JobCreateRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "run" | "retranslate" | "compile" | "check";
            /**
             * From
             * @description 起点阶段（只对 action=run 有效），取值 = §3.1 的 7 个阶段
             */
            from?: string | null;
            /**
             * Pages
             * @description 页码范围（只对 action=run 有效），如 "1-3,5"
             */
            pages?: string | null;
            /**
             * Dual
             * @description 是否生成 dual（双语）PDF（action=run）
             * @default false
             */
            dual: boolean;
            /**
             * Profile
             * @description provider profile id（命令由服务端解析，永不回传）；action=run/check 必填，action=compile 不需要（不调翻译/审查）
             */
            profile?: string | null;
            /**
             * Scope
             * @description 编译范围（只对 action=compile 有效，缺省 full）；v1 页级编译按已批准设计回退全量，响应/记录里给 requested_scope/effective_scope/downgrade_reason
             */
            scope?: ("full" | "pages") | null;
            /**
             * Base Revision
             * @description 期望的草稿 revision（只对 action=compile 有效）：与当前不一致 → 409 revision_conflict，防止编译一个已经不是最新的草稿
             */
            base_revision?: number | null;
            /**
             * Use Glossary
             * @description 是否给这次翻译注入全局词表（只对 action=run 且真的跑 translate 阶段有效）。客户端只给这个布尔；词表内容与文件路径全在服务端（``<store_base>/.bdt-serve/glossary.csv`` → ``--glossaries``）；词表为空或该 action 不跑翻译时一律不注入
             * @default true
             */
            use_glossary: boolean;
        };
        /**
         * JobRecord
         * @description 一个 job 的持久化快照；**同时**是 ``GET /jobs/{jid}`` 的响应体。
         *
         *     一份模型两处用（快照文件 = 响应体），避免"存储字段"与"响应字段"两套字段漂移。
         *     ``pid``/``pgid`` 只在运行中有值（终态清空：不再持有进程身份）；``boot_id`` 与
         *     ``spawn_marker`` 是重启恢复用的身份指纹，不是命令原文。
         */
        JobRecord: {
            /** Job Id */
            job_id: string;
            /** Did */
            did: string;
            /**
             * Action
             * @enum {string}
             */
            action: "run" | "retranslate" | "compile" | "check";
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "canceled" | "interrupted";
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** From Stage */
            from_stage?: string | null;
            /** Profile */
            profile?: string | null;
            /** Pages */
            pages?: string | null;
            /**
             * Dual
             * @default false
             */
            dual: boolean;
            /**
             * Use Glossary
             * @default false
             */
            use_glossary: boolean;
            /** Requested Scope */
            requested_scope?: string | null;
            /** Effective Scope */
            effective_scope?: string | null;
            /** Downgrade Reason */
            downgrade_reason?: string | null;
            /** Trigger */
            trigger?: ("debounce" | "manual") | null;
            /** Paragraph Id */
            paragraph_id?: string | null;
            /** Candidate Id */
            candidate_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Envelope */
            envelope?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Pid */
            pid?: number | null;
            /** Pgid */
            pgid?: number | null;
            /** Cancel Requested At */
            cancel_requested_at?: string | null;
            /** Boot Id */
            boot_id?: string | null;
            /** Spawn Marker */
            spawn_marker?: string | null;
            /** Interrupted Reason */
            interrupted_reason?: string | null;
        };
        /**
         * ParagraphItem
         * @description ``GET /api/v1/documents/{did}/paragraphs`` 的单个段落（多产物 join）。
         */
        ParagraphItem: {
            /** Id */
            id: string;
            /** Page */
            page?: number | null;
            /** Layout Label */
            layout_label?: string | null;
            /** Source */
            source?: string | null;
            /** Target */
            target?: string | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Layout Status */
            layout_status: string;
        };
        /**
         * PdfOutput
         * @description ``run_state`` 记录的 PDF 产物（相对 workdir 的路径）。
         */
        PdfOutput: {
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Bytes */
            bytes?: number | null;
        };
        /**
         * ProfileListItem
         * @description ``GET /profiles`` 的条目 / ``PUT /profiles`` 的响应（api.md §3.5）。
         *
         *     **没有命令字段**：translator/reviewer 命令字符串只存在于服务端（可能内嵌密钥），
         *     前端只用 ``id`` 提交 job、用 ``label`` 显示。
         */
        ProfileListItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Has Translator */
            has_translator: boolean;
            /** Has Reviewer */
            has_reviewer: boolean;
        };
        /**
         * ProfileUpdateRequest
         * @description ``PUT /profiles`` 的请求体（api.md §3.5）。
         *
         *     字段**缺席**与显式 ``null`` 不同：缺席 = 不动这个字段，``null``/空串 = 删掉它
         *     （删成空条目就是删整个 profile）。``translator``/``reviewer``/``api_key`` 之类字段
         *     **不在**模型里：收到了由路由层 422 ``forbidden_field`` 拒掉，不静默忽略。
         */
        ProfileUpdateRequest: {
            /**
             * Id
             * @description profile id（[a-z0-9-]{1,64}）
             */
            id: string;
            /**
             * Label
             * @description 显示名；null/空串 = 清掉（显示时回退 id 的人性化形式）
             */
            label?: string | null;
            /**
             * Translator Script
             * @description translator 脚本路径引用（scripts/<name>，必须在白名单目录内）；null = 删该字段
             */
            translator_script?: string | null;
            /**
             * Reviewer Script
             * @description reviewer 脚本路径引用（scripts/<name>，必须在白名单目录内）；null = 删该字段
             */
            reviewer_script?: string | null;
        };
        /**
         * QualityCheck
         * @description 质量门禁里的 check 结论（api.md §3.2）。
         *
         *     ``verdict`` 取 ``run_state.quality.check.verdict``（check 阶段合并 review_verdict +
         *     layout_lint + link_audit 后的**门禁结论**），缺失才退回 ``review_verdict.json``
         *     自己的 verdict（那是结构审查的结论，不含 lint/link）。
         *     ``blockers``/``warnings`` 是 ``review_verdict.json`` 的原样列表。
         */
        QualityCheck: {
            /** Verdict */
            verdict: string;
            /**
             * Blockers
             * @default []
             */
            blockers: unknown[];
            /**
             * Warnings
             * @default []
             */
            warnings: unknown[];
            /**
             * Reasons
             * @default []
             */
            reasons: unknown[];
            /** At */
            at?: string | null;
        };
        /**
         * QualityReviewer
         * @description reviewer 结论（api.md §3.2）。
         *
         *     只取 ``run_state.quality.reviewer``：它有时写 ``status``
         *     （``waiting_for_reviewer`` / ``needs_human_review`` / ``needs_fix``），有时只有
         *     ``verdict``（``pass`` / ``needs_fix``，来自 ``agent/agent_review.json``）。
         *     两个都没有（review 阶段没跑过）→ ``not_run``。
         */
        QualityReviewer: {
            /** Status */
            status: string;
            /**
             * Fix Rounds
             * @default {}
             */
            fix_rounds: {
                [key: string]: number;
            };
            /** At */
            at?: string | null;
        };
        /**
         * QualityStatus
         * @description ``quality``：门禁结论 + reviewer 结论 + 能否算成功。
         *
         *     ``pipeline_ok`` 只有在 check 门禁 ``pass`` **且** reviewer ``pass`` 时才为 true：
         *     缺任一侧结论、或任一侧非绿都按 false 报（"编译成功"不得让它变 true）。
         */
        QualityStatus: {
            check: components["schemas"]["QualityCheck"];
            reviewer: components["schemas"]["QualityReviewer"];
            /** Pipeline Ok */
            pipeline_ok: boolean;
        };
        /**
         * StageStateItem
         * @description 单个阶段的状态与时间。
         */
        StageStateItem: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Ok */
            ok?: boolean | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Timing Source */
            timing_source?: ("manifest" | "run_state") | null;
        };
        /**
         * StageStateResponse
         * @description ``GET /api/v1/documents/{did}/stage-state``：7 个固定阶段。
         */
        StageStateResponse: {
            /** Did */
            did: string;
            /** Run Id */
            run_id?: string | null;
            /** Stages */
            stages: components["schemas"]["StageStateItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionItem
         * @description 一条版本归档（``<workdir>/.bdt-serve/versions.json`` 的条目 / §3.7 的列表元素）。
         *
         *     ``revision`` = 这次编译捕获的草稿 revision（与 ``compile.revision`` 同源）；
         *     ``artifact_name`` 是发布时的**裸文件名**（前端据此给下载落盘名）。
         */
        VersionItem: {
            /** Revision */
            revision: number;
            /** Created At */
            created_at: string;
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "debounce" | "manual";
            /** Artifact Name */
            artifact_name: string;
            /** Bytes */
            bytes: number;
            /** Sha256 Head */
            sha256_head: string;
            quality: components["schemas"]["VersionQuality"];
        };
        /**
         * VersionQuality
         * @description 版本归档时刻的质量快照（api.md §3.7）。
         *
         *     **只记录不门禁**：``pipeline_ok=false``（如 ``check_verdict=needs_fix``）的版本照样
         *     可下载，前端黄标；归档不看质量，它只如实记下发布那一刻详情端点说的结论
         *     （``views.quality_status`` 的同一实现）。
         */
        VersionQuality: {
            /** Check Verdict */
            check_verdict: string;
            /** Pipeline Ok */
            pipeline_ok: boolean;
        };
        /**
         * VersionsResponse
         * @description ``GET /documents/{did}/versions``：版本清单 + 当前编译上下文（api.md §3.7）。
         *
         *     ``items`` **新 → 旧**；``current_revision``/``stale`` 取自 ``compile``（§3.2）：当前
         *     可下载的那一版不是清单里的最新行而**恒**是 ``compile.artifact``（``output/`` 的最新
         *     发布）。``items`` 为空 = 从没编译成功过（不是错误）。
         */
        VersionsResponse: {
            /** Did */
            did: string;
            /**
             * Current Revision
             * @default 0
             */
            current_revision: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["VersionItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListItem"][];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploaded"];
                };
            };
            /** @description upload_conflict：连续 50 个候选目录名都被占用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description file_too_large：超过 200MB 上限 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid_pdf：缺文件名或前 5 字节不是 %PDF- */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_document_api_v1_documents__did__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stage_state_api_v1_documents__did__stage_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paragraphs_api_v1_documents__did__paragraphs_get: {
        parameters: {
            query?: {
                /** @description 页码过滤（1 基 PDF 页码） */
                page?: number | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParagraphItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geometry_api_v1_documents__did__geometry_get: {
        parameters: {
            query: {
                /** @description parse = 识别/原文 bbox；layout = 译文排版 bbox */
                kind: "parse" | "layout";
                /** @description 页码过滤（1 基 PDF 页码） */
                page?: number | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_check_api_v1_documents__did__check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_v1_documents__did__events_get: {
        parameters: {
            query?: {
                /** @description 扫描起点：只返回 seq 大于它的事件（同一 run 内有意义） */
                after_seq?: number;
                /** @description 本页最多扫描多少条事件（默认 500，上限 2000） */
                limit?: number;
                /** @description 只返回该阶段的事件（过滤不影响游标推进） */
                stage?: string | null;
                /** @description 只返回该 kind 的事件（过滤不影响游标推进） */
                kind?: string | null;
                /** @description run id（默认最新 run）；形状必须是 <UTC时间戳>Z-<6位十六进制> */
                run_id?: string | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_documents__did__events_stream_get: {
        parameters: {
            query?: {
                /** @description 扫描起点：只返回 seq 大于它的事件（同一 run 内有意义） */
                after_seq?: number | null;
                /** @description run id（默认最新 run）；形状必须是 <UTC时间戳>Z-<6位十六进制> */
                run_id?: string | null;
            };
            header?: {
                /** @description <run_id>:<seq>，用于断线续传 */
                "Last-Event-ID"?: string | null;
            };
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 帧流（event / id / data 三行 + 空行） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_documents__did__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_documents__did__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 产物短名 = workdir 相对路径，如 output/paper.mono.pdf、agent/translated.md、FINAL_REPORT.md；只接受清单内的白名单名字 */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 产物字节（Content-Type 按 kind 决定） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "application/json": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_documents__did__jobs_get: {
        parameters: {
            query?: {
                /** @description 只看该状态的 job（省略 = 全部，新 → 旧） */
                status?: ("queued" | "running" | "succeeded" | "failed" | "canceled" | "interrupted") | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
            /** @description document_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_documents__did__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description document_busy / revision_conflict（compile 的 base_revision 不符） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unknown_profile / action_not_available / forbidden_field */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_job_api_v1_jobs__jid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description job id（``j_`` + 26 字符 ULID 风格；来自 POST jobs 的响应） */
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description job_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__jid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description job id（``j_`` + 26 字符 ULID 风格；来自 POST jobs 的响应） */
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已终态：幂等返回当前状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description job_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_documents__did__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description document_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_api_v1_documents__did__draft_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description document_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description document_busy */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_draft_api_v1_documents__did__draft_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description document_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description document_busy / revision_conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description draft_invalid / validation_error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retranslate_api_v1_documents__did__paragraphs__pid__retranslate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 段落 id（与 GET /paragraphs 的 id 一致，如 P05-002） */
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateRetranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateJobAccepted"];
                };
            };
            /** @description document_not_found / paragraph_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description document_busy */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description profile_missing / unknown_profile / forbidden_field */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_candidates_api_v1_documents__did__paragraphs__pid__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 段落 id（与 GET /paragraphs 的 id 一致，如 P05-002） */
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListResponse"];
                };
            };
            /** @description document_not_found / paragraph_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adopt_candidate_api_v1_documents__did__paragraphs__pid__candidates__cid__adopt_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 段落 id（与 GET /paragraphs 的 id 一致，如 P05-002） */
                pid: string;
                /** @description 候选 id（``c_`` + 4 位十进制；来自 retranslate / candidates 响应） */
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description document_not_found / candidate_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description document_busy / candidate_decided / candidate_not_ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description draft_invalid（候选文本写不进草稿时不静默） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject_candidate_api_v1_documents__did__paragraphs__pid__candidates__cid__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 段落 id（与 GET /paragraphs 的 id 一致，如 P05-002） */
                pid: string;
                /** @description 候选 id（``c_`` + 4 位十进制；来自 retranslate / candidates 响应） */
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateItem"];
                };
            };
            /** @description document_not_found / candidate_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description candidate_decided */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_documents__did__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionsResponse"];
                };
            };
            /** @description document_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_version_api_v1_documents__did__versions__revision__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 版本号 = 该版本的编译 revision（十进制整数；来自 `GET /versions` 的 `items[].revision`） */
                revision: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 该版本的 PDF 字节 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description document_not_found / version_not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListItem"][];
                };
            };
        };
    };
    put_profile_api_v1_profiles_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListItem"];
                };
            };
            /** @description forbidden_field / script_path_forbidden / validation_error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_glossary_api_v1_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
        };
    };
    put_glossary_api_v1_glossary_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossaryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
            /** @description glossary_invalid / validation_error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_glossary_api_v1_glossary_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryResponse"];
                };
            };
        };
    };
}
