/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探测 + 可见文档数
         * @description 根目录在运行期被删/不可读时返回 503 ``root_missing``（而不是谎报 ok）。
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 文档列表
         * @description 枚举可见 workdir 的概要：阶段状态、页数/段数/已译段数、最近活动时间。产物缺失的字段为 null（不是 0），坏产物不影响其它文档。
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 文档元信息
         * @description 元信息 + 质量状态 + 编译状态。质量与编译**分开**报：quality.pipeline_ok 只有 check 门禁与 reviewer 都 pass 才为 true；compile 在 W02 没有真实编译产物，固定 status=none / revision=0。
         */
        get: operations["get_document_api_v1_documents__did__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/stage-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 7 阶段状态与真实耗时
         * @description 阶段名固定为 parse → translate → apply → build → check → review → report。起止时间优先取最新 run 的 manifest.json（token 为 manifest），manifest 缺该段时回退 run_state.json 的 at + duration_s（token 为 run_state，起点由完成时刻与实测耗时反推）。
         */
        get: operations["get_stage_state_api_v1_documents__did__stage_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/paragraphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 段落面板数据（原文/译文/排版 join）
         * @description 以段落 id 左连接 anchors / translated.jsonl / layout_geometry / parse 快照，数量不一致时缺侧为 null（不假设相等）。page 为 1 基 PDF 页码。
         */
        get: operations["get_paragraphs_api_v1_documents__did__paragraphs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * bbox 几何（parse 快照 / layout 几何）
         * @description kind=parse 读最新 run 的 parse 段落实体，box 是 pdf_topleft（y 向下）；kind=layout 读 layout_geometry.json，box 是 pdf_native（y 向上）并附 page_info 的 cropbox。两套坐标系统**不做转换**，由前端按 coord_system 换算。缺对应产物时返回 404（snapshot_unavailable / geometry_unavailable），不用空数组冒充成功。
         */
        get: operations["get_geometry_api_v1_documents__did__geometry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 结构审查 / 排版 lint / 链接审计
         * @description 三份检查产物原样透传（不裁剪字段），available 标志说明各自是否可用（旧 workdir 可能缺项）。
         */
        get: operations["get_check_api_v1_documents__did__check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 事件分页
         * @description 读 events.jsonl 的一页（默认最新 run，?run_id= 可指定）。next_after_seq 是**扫描位置**：即使 stage/kind 过滤后本页 0 条也会推进。文件尾部的半行不发布，损坏行跳过。没有任何 run 归档 → 404 events_unavailable。
         */
        get: operations["get_events_api_v1_documents__did__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 事件实时流（SSE）
         * @description text/event-stream：每条形如 `event: <kind>` / `id: <run_id>:<seq>` / `data: <事件 JSON>`；15s 无事件发一行 `: ping` 注释。断线续传用 Last-Event-ID（`<run_id>:<seq>`）或 `?after_seq=`；换 run 时必须带新的 ?run_id=。没有 run 归档 → 404 events_unavailable（错误走统一 JSON 信封，不是 SSE 帧）。
         */
        get: operations["stream_events_api_v1_documents__did__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 可下载产物清单
         * @description 白名单产物的清单（name/path/kind/size/mtime），name 就是下载 URL 的 {name}。白名单 = 根级 FINAL_REPORT.md(report) / source.pdf(source) + output/*.pdf(pdf) + agent/*.md(markdown) 与 agent/*.json|*.jsonl(json)；不递归子目录，debug/ 与 run 临时产物不在其中。没有任何产物时返回空数组（清单本身可用且确实为空，不是缺产物）。
         */
        get: operations["list_artifacts_api_v1_documents__did__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{did}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下载产物（支持 Range/HEAD）
         * @description 只允许清单内的白名单名字；越界（`..`/绝对路径/符号链接指向 workdir 外）与不在白名单内的名字都返回 404 ``artifact_not_found``，不泄露存在性。支持 `Range: bytes=a-b`（206 + Content-Range，pdf.js 依赖）与 HEAD。
         */
        get: operations["get_artifact_api_v1_documents__did__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactItem
         * @description ``GET /api/v1/documents/{did}/artifacts`` 的一件产物（api.md §1.5）。
         *
         *     ``name`` 既是稳定短名也是下载键（``artifacts/{name}`` 的路径参数）：workdir
         *     相对路径，如 ``output/paper.mono.pdf`` / ``agent/translated.md`` / ``source.pdf``。
         *     ``path`` 与 ``name`` 同值（沿用 W02 ``PdfOutput.path`` 的"相对 workdir"约定，
         *     不是服务端绝对路径）。
         *
         *     W03 没有草稿编译产物（草稿与编译修订号按 §3.2 在 W09 落地），所以 §1.5 提到的
         *     ``revision`` 字段在这里暂不出现 —— 没有真实来源就不塞假值。
         */
        ArtifactItem: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "markdown" | "json" | "report" | "source";
            /** Size */
            size: number;
            /** Mtime */
            mtime: string;
        };
        /**
         * CheckAvailability
         * @description check 三源产物各自是否可用（旧 workdir 可能缺某项）。
         */
        CheckAvailability: {
            /** Review */
            review: boolean;
            /** Lint */
            lint: boolean;
            /** Link */
            link: boolean;
        };
        /**
         * CheckResponse
         * @description ``GET /api/v1/documents/{did}/check``：三源原样透传（不裁剪字段）。
         */
        CheckResponse: {
            /** Did */
            did: string;
            /** Review Verdict */
            review_verdict?: {
                [key: string]: unknown;
            } | null;
            /** Layout Lint */
            layout_lint?: {
                [key: string]: unknown;
            } | null;
            /** Link Audit */
            link_audit?: {
                [key: string]: unknown;
            } | null;
            available: components["schemas"]["CheckAvailability"];
        };
        /**
         * CompileStatus
         * @description ``compile``：服务端管理的草稿编译产物（api.md §3.2）。
         *
         *     W02 没有真实编译产物（草稿编译在 W09）：固定 ``status="none"`` / ``revision=0`` /
         *     ``stale=false`` / ``artifact=null``。``run_state`` 里 ``bdt run`` 直接产出的 PDF
         *     不是编译 revision，已放在 :attr:`DocumentDetail.pdf`，不在这里冒充编译结果。
         */
        CompileStatus: {
            /**
             * Status
             * @default none
             * @enum {string}
             */
            status: "none" | "running" | "ok" | "failed";
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Artifact */
            artifact?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DocumentAvailability
         * @description 哪些 workdir 产物可用（缺失或损坏 → false，对应字段为 null）。
         */
        DocumentAvailability: {
            /** Run State */
            run_state: boolean;
            /** Anchors */
            anchors: boolean;
            /** Translated */
            translated: boolean;
            /** Geometry */
            geometry: boolean;
            /** Parse Snapshot */
            parse_snapshot: boolean;
            /** Review Verdict */
            review_verdict: boolean;
            /** Layout Lint */
            layout_lint: boolean;
            /** Link Audit */
            link_audit: boolean;
        };
        /**
         * DocumentDetail
         * @description ``GET /api/v1/documents/{did}``：列表项字段 + 元信息。
         */
        DocumentDetail: {
            /** Did */
            did: string;
            /** Title */
            title?: string | null;
            /** Pages */
            pages?: number | null;
            /** Paragraph Count */
            paragraph_count?: number | null;
            /** Translated Count */
            translated_count?: number | null;
            /** Stage Summary */
            stage_summary: {
                [key: string]: string;
            };
            /** Updated At */
            updated_at?: string | null;
            pdf: components["schemas"]["DocumentPdf"];
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            quality: components["schemas"]["QualityStatus"];
            compile: components["schemas"]["CompileStatus"];
            available: components["schemas"]["DocumentAvailability"];
        };
        /**
         * DocumentListItem
         * @description 文档列表项 / 详情里的公共计数部分（``GET /api/v1/documents``）。
         *
         *     ``None`` = 对应产物缺失或损坏（不是 0）：缺 ``translated.jsonl`` 时
         *     ``translated_count`` 为 null，产物存在但没译文才是 0。
         */
        DocumentListItem: {
            /** Did */
            did: string;
            /** Title */
            title?: string | null;
            /** Pages */
            pages?: number | null;
            /** Paragraph Count */
            paragraph_count?: number | null;
            /** Translated Count */
            translated_count?: number | null;
            /** Stage Summary */
            stage_summary: {
                [key: string]: string;
            };
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DocumentPdf
         * @description 详情里的 PDF 来源与产物路径。
         */
        DocumentPdf: {
            /** Source */
            source?: string | null;
            /**
             * Outputs
             * @default []
             */
            outputs: components["schemas"]["PdfOutput"][];
        };
        /**
         * EventsPage
         * @description ``GET /api/v1/documents/{did}/events``：一页事件 + 续传游标（api.md §1.3）。
         *
         *     ``run_id`` 是本页事件**实际来源**的 run。``seq`` 只在单 run 内单调递增，游标语义
         *     是 ``(run_id, seq)``（api.md §1.3），前端要靠它组 SSE 的 ``Last-Event-ID``；
         *     这是对 §1.3 响应形状的 additive 扩展（三个原键不变）。
         *
         *     ``next_after_seq`` 是**扫描位置**而不是匹配位置：带 ``stage``/``kind`` 过滤时
         *     即使本页 0 条匹配也必须推进，否则过滤条件会卡住轮询。``events`` 是事件原样
         *     透传（``{seq, at, stage, kind, data}``，不裁剪 ``data``）。
         */
        EventsPage: {
            /** Run Id */
            run_id: string;
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
            /** Next After Seq */
            next_after_seq: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * GeometryResponse
         * @description ``GET /api/v1/documents/{did}/geometry``：bbox 数据。
         *
         *     ``kind=parse`` 用 ``run_id``/``entities``/``relations``（快照，``pdf_topleft``）；
         *     ``kind=layout`` 用 ``pages``/``paragraphs``/``page_info``（几何产物，``pdf_native``）。
         *     两类的 box 坐标系不同且**不做转换**，前端按 ``coord_system`` 自行换算。
         */
        GeometryResponse: {
            /** Did */
            did: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "parse" | "layout";
            /**
             * Coord System
             * @enum {string}
             */
            coord_system: "pdf_topleft" | "pdf_native";
            /** Page */
            page?: number | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Entities
             * @default []
             */
            entities: {
                [key: string]: unknown;
            }[];
            /**
             * Relations
             * @default []
             */
            relations: {
                [key: string]: unknown;
            }[];
            /** Pages */
            pages?: number | null;
            /**
             * Paragraphs
             * @default []
             */
            paragraphs: {
                [key: string]: unknown;
            }[];
            /**
             * Page Info
             * @default []
             */
            page_info: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /api/v1/health``：进程存活 + 当前可见文档数。
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Api
             * @default /api/v1
             */
            api: string;
            /** Version */
            version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "root" | "workdir";
            /** Root */
            root: string;
            /** Documents */
            documents: number;
        };
        /**
         * ParagraphItem
         * @description ``GET /api/v1/documents/{did}/paragraphs`` 的单个段落（多产物 join）。
         */
        ParagraphItem: {
            /** Id */
            id: string;
            /** Page */
            page?: number | null;
            /** Layout Label */
            layout_label?: string | null;
            /** Source */
            source?: string | null;
            /** Target */
            target?: string | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Layout Status */
            layout_status: string;
        };
        /**
         * PdfOutput
         * @description ``run_state`` 记录的 PDF 产物（相对 workdir 的路径）。
         */
        PdfOutput: {
            /** Path */
            path: string;
            /** Exists */
            exists: boolean;
            /** Bytes */
            bytes?: number | null;
        };
        /**
         * QualityCheck
         * @description 质量门禁里的 check 结论（api.md §3.2）。
         *
         *     ``verdict`` 取 ``run_state.quality.check.verdict``（check 阶段合并 review_verdict +
         *     layout_lint + link_audit 后的**门禁结论**），缺失才退回 ``review_verdict.json``
         *     自己的 verdict（那是结构审查的结论，不含 lint/link）。
         *     ``blockers``/``warnings`` 是 ``review_verdict.json`` 的原样列表。
         */
        QualityCheck: {
            /** Verdict */
            verdict: string;
            /**
             * Blockers
             * @default []
             */
            blockers: unknown[];
            /**
             * Warnings
             * @default []
             */
            warnings: unknown[];
            /**
             * Reasons
             * @default []
             */
            reasons: unknown[];
            /** At */
            at?: string | null;
        };
        /**
         * QualityReviewer
         * @description reviewer 结论（api.md §3.2）。
         *
         *     只取 ``run_state.quality.reviewer``：它有时写 ``status``
         *     （``waiting_for_reviewer`` / ``needs_human_review`` / ``needs_fix``），有时只有
         *     ``verdict``（``pass`` / ``needs_fix``，来自 ``agent/agent_review.json``）。
         *     两个都没有（review 阶段没跑过）→ ``not_run``。
         */
        QualityReviewer: {
            /** Status */
            status: string;
            /**
             * Fix Rounds
             * @default {}
             */
            fix_rounds: {
                [key: string]: number;
            };
            /** At */
            at?: string | null;
        };
        /**
         * QualityStatus
         * @description ``quality``：门禁结论 + reviewer 结论 + 能否算成功。
         *
         *     ``pipeline_ok`` 只有在 check 门禁 ``pass`` **且** reviewer ``pass`` 时才为 true：
         *     缺任一侧结论、或任一侧非绿都按 false 报（"编译成功"不得让它变 true）。
         */
        QualityStatus: {
            check: components["schemas"]["QualityCheck"];
            reviewer: components["schemas"]["QualityReviewer"];
            /** Pipeline Ok */
            pipeline_ok: boolean;
        };
        /**
         * StageStateItem
         * @description 单个阶段的状态与时间。
         */
        StageStateItem: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Ok */
            ok?: boolean | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Timing Source */
            timing_source?: ("manifest" | "run_state") | null;
        };
        /**
         * StageStateResponse
         * @description ``GET /api/v1/documents/{did}/stage-state``：7 个固定阶段。
         */
        StageStateResponse: {
            /** Did */
            did: string;
            /** Run Id */
            run_id?: string | null;
            /** Stages */
            stages: components["schemas"]["StageStateItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListItem"][];
                };
            };
        };
    };
    get_document_api_v1_documents__did__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stage_state_api_v1_documents__did__stage_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paragraphs_api_v1_documents__did__paragraphs_get: {
        parameters: {
            query?: {
                /** @description 页码过滤（1 基 PDF 页码） */
                page?: number | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParagraphItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geometry_api_v1_documents__did__geometry_get: {
        parameters: {
            query: {
                /** @description parse = 识别/原文 bbox；layout = 译文排版 bbox */
                kind: "parse" | "layout";
                /** @description 页码过滤（1 基 PDF 页码） */
                page?: number | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_check_api_v1_documents__did__check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_v1_documents__did__events_get: {
        parameters: {
            query?: {
                /** @description 扫描起点：只返回 seq 大于它的事件（同一 run 内有意义） */
                after_seq?: number;
                /** @description 本页最多扫描多少条事件（默认 500，上限 2000） */
                limit?: number;
                /** @description 只返回该阶段的事件（过滤不影响游标推进） */
                stage?: string | null;
                /** @description 只返回该 kind 的事件（过滤不影响游标推进） */
                kind?: string | null;
                /** @description run id（默认最新 run）；形状必须是 <UTC时间戳>Z-<6位十六进制> */
                run_id?: string | null;
            };
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_documents__did__events_stream_get: {
        parameters: {
            query?: {
                /** @description 扫描起点：只返回 seq 大于它的事件（同一 run 内有意义） */
                after_seq?: number | null;
                /** @description run id（默认最新 run）；形状必须是 <UTC时间戳>Z-<6位十六进制> */
                run_id?: string | null;
            };
            header?: {
                /** @description <run_id>:<seq>，用于断线续传 */
                "Last-Event-ID"?: string | null;
            };
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 帧流（event / id / data 三行 + 空行） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_documents__did__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_documents__did__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 id：workdir 目录名（单段，解析结果必须在服务根目录内） */
                did: string;
                /** @description 产物短名 = workdir 相对路径，如 output/paper.mono.pdf、agent/translated.md、FINAL_REPORT.md；只接受清单内的白名单名字 */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 产物字节（Content-Type 按 kind 决定） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "application/json": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
