"""Auto-generated by scripts/gen_cmap_manifest.py. Do not edit by hand.

Pinned sha256 + byte size for every bundled CMap pickle. Used by the
runtime CMap loader to refuse any non-bundled or tampered .pickle.gz
(GHSA-m8gf-v64p-gfmg).
"""

from __future__ import annotations

# filename -> (sha256_hex, size_bytes)
CMAP_MANIFEST: dict[str, tuple[str, int]] = {
    "78-EUC-H.pickle.gz": (
        "a7e1f9a0941e66f56d06bdd4b2f108237a66b5501b7fa4b5e9a09a96475457e4",
        20532,
    ),
    "78-EUC-V.pickle.gz": (
        "a547e21cce698d2a814cbed4aee94a46523f9a8fe8f0ca2fd1450173df6e98ec",
        20551,
    ),
    "78-H.pickle.gz": (
        "09635f0a38adecb373e750ae64f483f1b6d45d064373eb3417b94b65f248c5d6",
        19882,
    ),
    "78-RKSJ-H.pickle.gz": (
        "5ac22384b98196f02605357927367b88a9afd537b1504eb52a7b816733163a00",
        22969,
    ),
    "78-RKSJ-V.pickle.gz": (
        "109240b21a496ff060dd7ededca78da5e3803157c3c0fb06aba17347ca58f200",
        22990,
    ),
    "78-V.pickle.gz": (
        "ef2bbeb29d9e937f282b9129279ee39be3d3c29d0b062c1bc71a69214c687640",
        19883,
    ),
    "78ms-RKSJ-H.pickle.gz": (
        "8ce2ed9bbca6e39026182320ea2b0e18a902c89534ebc0b6aaaf8f585e1749c4",
        25942,
    ),
    "78ms-RKSJ-V.pickle.gz": (
        "c377b0eebdcd6460d732c45ceb3ec00d0b408834678c129c0e9ac0d52f4dec67",
        25964,
    ),
    "83pv-RKSJ-H.pickle.gz": (
        "6a8b5267890592b9185a84cd43408d56690b93c7101bd0a9bf5a26a1f39d8031",
        26305,
    ),
    "83pv-RKSJ-V.pickle.gz": (
        "dd273ac3ca018083886994691d3453327a0ddd87ebfe774e9b573a691f175407",
        26305,
    ),
    "90ms-RKSJ-H.pickle.gz": (
        "5402ca275ff5cdb810186727547e3874b31461857ab48c26986c4130b5c3d9cf",
        25732,
    ),
    "90ms-RKSJ-V.pickle.gz": (
        "67ec3b0d5565445492b12f7b5eab3017b84fd46af7736f5c331e54264bd2fb49",
        25757,
    ),
    "90msp-RKSJ-H.pickle.gz": (
        "a85bc8750cef621467aa476cd999e6bc5e66c42aaf1c74a08632e6c0f99955b3",
        25670,
    ),
    "90msp-RKSJ-V.pickle.gz": (
        "48eb9737b2bb036499f1dbbb6821e74f218f5fdbff05825f2e18de55174165ec",
        25688,
    ),
    "90pv-RKSJ-H.pickle.gz": (
        "08c6463e60b4b24ba711c844c1d2abaee0d3e5f0f9452198ebeee161281a88f1",
        24226,
    ),
    "90pv-RKSJ-V.pickle.gz": (
        "0b1c838def87b351b1c16663465ffb1800977a274d842b5932ec64ceead32020",
        24021,
    ),
    "Add-H.pickle.gz": (
        "4b2023beece24c938e9c6cb4c355be88d19b5b8b0dbd4dee64ef069910463441",
        21027,
    ),
    "Add-RKSJ-H.pickle.gz": (
        "378003e40c4506327f325a0b4debda46934ca9035edded63acca56bc5576444b",
        24275,
    ),
    "Add-RKSJ-V.pickle.gz": (
        "558157deeb898de99fe33281fdfacda5c95e256513a4ba44579a8862fad4b6d5",
        24079,
    ),
    "Add-V.pickle.gz": (
        "1a5ab752aa4cd4acb12cee31a9b5650b917fd10fbe0a8b17aa9a57bcf065bb86",
        20874,
    ),
    "B5-H.pickle.gz": (
        "990e52c7459b0d9c3a6f3491611d1589af5980398e06ee7ed9b2f0de39dbfef4",
        42594,
    ),
    "B5-V.pickle.gz": (
        "4c330ad420434c68e27b27b16c4af7503a0d94b437ef8c4554356bb3b41eaf8a",
        42549,
    ),
    "B5pc-H.pickle.gz": (
        "01b777e8d2f67cb99c204e8792e810c2a4dc39760416810371d1fb6761940e16",
        42602,
    ),
    "B5pc-V.pickle.gz": (
        "5dbfc4d888ccd5756275e455994f1a287288c4d8dfe24c845bd5a5209481022f",
        42557,
    ),
    "CNS-EUC-H.pickle.gz": (
        "d7ae970c305e97bbc5d9a12e396fcf5d3dd53563d41be41e4b69ecbbc793b9e5",
        56990,
    ),
    "CNS-EUC-V.pickle.gz": (
        "02f3d2e82617d952599548fcc0ea9f6d71c65c4709dcb96715f40901aca94491",
        56943,
    ),
    "CNS1-H.pickle.gz": (
        "c525b152e96b97a958b87a9fdc347039ec9188892a8d5d78e29f4543afc843e9",
        17615,
    ),
    "CNS1-V.pickle.gz": (
        "fd870d3e08bf4900fefd2db701ccf1b742ea45d34c7af95a690689cec66164a7",
        17564,
    ),
    "CNS2-H.pickle.gz": (
        "15500f341d9958d0f357ccd95da936564c2f46ec3f8f913a40ce365def58c119",
        21723,
    ),
    "CNS2-V.pickle.gz": (
        "2cbc6eab5d03a1e63239c33d316afa3b9c5832b74b4488f7408492347e578a29",
        21723,
    ),
    "ETHK-B5-H.pickle.gz": (
        "0b86cbe3eb115bf7aae0912686e882fb02c05f700c511a6d713a8b0b1e60df94",
        59548,
    ),
    "ETHK-B5-V.pickle.gz": (
        "dc6ac1269d57d1455f7e79d76bfe2aabc361a17952f06c3cfd8ca9afebaa60c3",
        59481,
    ),
    "ETen-B5-H.pickle.gz": (
        "175b8e6478d641e17793c0c331f0d6ef60c2875eeec4a739135c742723acac98",
        43982,
    ),
    "ETen-B5-V.pickle.gz": (
        "02a8c5eb726baf1b9bb9313338d477c8ca200c4c06b2992e43dca6cbe7d44a12",
        43924,
    ),
    "ETenms-B5-H.pickle.gz": (
        "605d10c0da8336efe2294c7dcf7ac31d25af57b952b3484acfa6d94cb8faf2d0",
        320,
    ),
    "ETenms-B5-V.pickle.gz": (
        "0f5b39cb67547c61564883bbde8a7522eb4a284af0cee3b89fdff408630d5d5d",
        438,
    ),
    "EUC-H.pickle.gz": (
        "f04d25667260f5c1ac7cc3f58cd0aa8f8fe59bd2fde50ce0e2bc69d31f7ac3d2",
        20429,
    ),
    "EUC-V.pickle.gz": (
        "c02eae4e48a2cdfbb1ef38beb447412f7b210280183824c9d452ed189599257c",
        20455,
    ),
    "Ext-H.pickle.gz": (
        "607ffe278436167617315afe6f7b2ed4ca9a151dda18e0b8f669e208bd6abc6d",
        22272,
    ),
    "Ext-RKSJ-H.pickle.gz": (
        "27f2e877ca024cbde2bebafa39d3064ce2e82c9ba805f518e9cd0fb3c70ecf49",
        25721,
    ),
    "Ext-RKSJ-V.pickle.gz": (
        "f48ef5c0cd83e4d188f4780616a0fa5fd816f173888501804bcc511618853932",
        25750,
    ),
    "Ext-V.pickle.gz": (
        "7695e7bee7d24f6922f408851a6bf7cf8a31dd099b103feb9650e37647ba74fc",
        22307,
    ),
    "GB-EUC-H.pickle.gz": (
        "f921365e809fd33fc10711772741edd164a9a3ebd8a0bcabaf618bcb83d20f62",
        22118,
    ),
    "GB-EUC-V.pickle.gz": (
        "a9fea3f484a09b8ec3df9eaee3cd0dcb6c9890a18effeedd525d50551ce1cfb7",
        22111,
    ),
    "GB-H.pickle.gz": (
        "d5a495fef1298e43404bd7e981438ed78fe84f00480c119e554409c8a270a61c",
        21699,
    ),
    "GB-V.pickle.gz": (
        "3f937d193a912656ea76be2c4f4a655e8deb586cce4787c399c692357d0cbf0a",
        21694,
    ),
    "GBK-EUC-H.pickle.gz": (
        "8a8641fefbd6cf36216e4196433384d35d8d4fb3f2d167b3c1a1481968f30349",
        68254,
    ),
    "GBK-EUC-V.pickle.gz": (
        "ead3d321f45f5d401b32121a4c0053f452f624a923293e858334430e788d5331",
        68199,
    ),
    "GBK2K-H.pickle.gz": (
        "c01baa0c788f3daaaff556834d4d5e302141ebb7ec3f26d9d911866660b1902f",
        89917,
    ),
    "GBK2K-V.pickle.gz": (
        "6408bfd672c1ae6e7795c72e5bb9afeea0d2510cd9447a21c36e2fe807895115",
        89872,
    ),
    "GBKp-EUC-H.pickle.gz": (
        "3460acae8a9e40611bbc1182e4483582a76b04d4545319bd3f0a2a5bd83fadcf",
        68148,
    ),
    "GBKp-EUC-V.pickle.gz": (
        "e39baf790b0d93e8504fc4d49bef08e831840b44b2aba2bad221bd3e2fa7f0a8",
        68102,
    ),
    "GBT-EUC-H.pickle.gz": (
        "5edc55d60e14dcaaf092f97eb64fea126693b104f7fe82fd1b435f25f33a7f7a",
        23815,
    ),
    "GBT-EUC-V.pickle.gz": (
        "575cad798504695fdd390159235a6c4f754c4bc1c77c05817a9bdde3f05c89e4",
        23806,
    ),
    "GBT-H.pickle.gz": (
        "5cb25fe3e632be0bfef4ba3c17c32ff61008b8aa269819c72af2165f9f774cf8",
        23339,
    ),
    "GBT-V.pickle.gz": (
        "9ba16fb8a2f36664a1d6c6271f85bd1bd9e8f5018accb5c04a608db576344189",
        23322,
    ),
    "GBTpc-EUC-H.pickle.gz": (
        "3c825575cf38352884b2919543911fa8580977dbe2b01d66139b209d2744c67c",
        23650,
    ),
    "GBTpc-EUC-V.pickle.gz": (
        "ae293868c474ae87f7a31e24940f98bff892ea977e689eea86f4a10fec412abc",
        23647,
    ),
    "GBpc-EUC-H.pickle.gz": (
        "664d42d0377e588451132409f0b10c4c99497af41dc9abd85e48794308d44386",
        21945,
    ),
    "GBpc-EUC-V.pickle.gz": (
        "fa7badbe40d515b1cfeaf60158bf508a45f80d50414855fd18d03f371ba8f3a3",
        21956,
    ),
    "H.pickle.gz": (
        "650ef8348f3e2bb2a9e92250d79f0aed02b7301edf4d379578ea4d67ac02ca46",
        19781,
    ),
    "HKdla-B5-H.pickle.gz": (
        "6354699fe8b433c2ce539e652360cc7586378622d1163e50782d58a5e3e88943",
        45212,
    ),
    "HKdla-B5-V.pickle.gz": (
        "8309e0b1156f58911aa96eca0ede7bc0abdb9a3e0674855dc51380eb52b283d8",
        45167,
    ),
    "HKdlb-B5-H.pickle.gz": (
        "a95567ce70f8560f06d4301139cec9f048f975df0706d6956f4d856921be6d98",
        44853,
    ),
    "HKdlb-B5-V.pickle.gz": (
        "b14223f89de638c4b4da3aee90719f596239e0b49cdf44a95c2d49fc38177e54",
        44816,
    ),
    "HKgccs-B5-H.pickle.gz": (
        "0aacafc532de1fb9868d156a711de1d6ce57718fc7ee1625afdcf628ba6b279f",
        53104,
    ),
    "HKgccs-B5-V.pickle.gz": (
        "b133531f905dadd8227cb0179fb9eba066151f8f6d14bc40c629a18d9a7f944f",
        53050,
    ),
    "HKm314-B5-H.pickle.gz": (
        "7bd57f53cbb5ed1e8b246d8048a8b019ffeb9b9c2006d6f5684edc2f1e4a7910",
        43667,
    ),
    "HKm314-B5-V.pickle.gz": (
        "dff77fdfdfda8bdc23785f0b0da060e2b39ee7dac590360d07813f2be7eb9172",
        43618,
    ),
    "HKm471-B5-H.pickle.gz": (
        "208bc0e81043047c152dbadf811fbec3f52ef3d2b7f9a25b5e3e728eb1c51dbe",
        44187,
    ),
    "HKm471-B5-V.pickle.gz": (
        "19c95ab9b328fa3bfcc80f9776b1e76b26c6bb22269611b69918a643aa859cf2",
        44144,
    ),
    "HKscs-B5-H.pickle.gz": (
        "2d1a3463baaf3ee810905937aae63599d211f8d275b37dd899fbce375e32ff2e",
        59508,
    ),
    "HKscs-B5-V.pickle.gz": (
        "3535201facf28bbe553d262baea2f4e011946345eef1dd3f549db3ddb141a76c",
        59473,
    ),
    "Hankaku-H.pickle.gz": (
        "2fb3f131e6afd98d103f2a313e21c04a51421a46fb33f430781113a4aca11b53",
        840,
    ),
    "Hankaku-V.pickle.gz": (
        "b76bed506a5593a0c6e715e2e659b8e1b157decba02c426bbc39165e6a00d2a8",
        839,
    ),
    "Hiragana-H.pickle.gz": (
        "ad583a37dee55420e42020e4ac3628cc028975419383af393cc1f004700d0c7f",
        391,
    ),
    "Hiragana-V.pickle.gz": (
        "d3071b58cbf5f60c0b288c6d45a303bb259c55af87723ebb67dcaf41cb64ea1f",
        391,
    ),
    "KSC-EUC-H.pickle.gz": (
        "b992f8c87eacac9de8459e21148fda28f325df7d307cfb0ed960505c8006090b",
        24040,
    ),
    "KSC-EUC-V.pickle.gz": (
        "fbb3dfabe2dc653fd3654dd64b7fb92dbbaf8fe198ef53fcfc15b3b197fa6817",
        24078,
    ),
    "KSC-H.pickle.gz": (
        "6861fbeac9b5e8f1f26f745fe9139c8acd139753ad7de4c0bb0e5a203eec5f25",
        23563,
    ),
    "KSC-Johab-H.pickle.gz": (
        "b8fe203384cfb07ac8906ba74f0cd850396980b9699b2e1ff9c3b7218443feb6",
        55016,
    ),
    "KSC-Johab-V.pickle.gz": (
        "be98bd71b56eb9069cbfd4da52c9d16307577940361ee07ffa78b5993410f992",
        55041,
    ),
    "KSC-V.pickle.gz": (
        "21c15a7836958dd2346dda0fa47649d6a25e8c58afed82acaa02504723a522be",
        23644,
    ),
    "KSCms-UHC-H.pickle.gz": (
        "6e965d4a27bd5931fc77b646a129f0459bf4f855017346cd39b6df7410655695",
        51667,
    ),
    "KSCms-UHC-HW-H.pickle.gz": (
        "b54853e5cd6c30f96f941954fc1a078ad8b628b6dd012fea15c3e99ece402c23",
        51788,
    ),
    "KSCms-UHC-HW-V.pickle.gz": (
        "56dc639520f4e129e8b9eccb0ede9c3f30a7de49540256007199a554226c5717",
        51821,
    ),
    "KSCms-UHC-V.pickle.gz": (
        "e745b52cb1973599ff8d3e39c6df2a6a92413ccb3c9831ae3cfdb9136798c40e",
        51698,
    ),
    "KSCpc-EUC-H.pickle.gz": (
        "103dc40d5cb38aed5e990cc3cfd894ba1593ab94cce2803f48c6d55364111789",
        27769,
    ),
    "KSCpc-EUC-V.pickle.gz": (
        "f3c983d6c66ab0a1de779bbaa8b16e8280bcf75df54db4c41f4f3367bac5eeee",
        27820,
    ),
    "Katakana-H.pickle.gz": (
        "0081a9501b40879c63d6a276f90bca4ec0d6b05cc284d876e9a42849b75f6de6",
        404,
    ),
    "Katakana-V.pickle.gz": (
        "1aeaa3820d5b9dd6af61bed21690d5edd2d8e68d3f32810a515d72c11ba97146",
        404,
    ),
    "NWP-H.pickle.gz": (
        "f8b04990c741e36eea61eb5f8d13bc99f5c85e3a74250c24ca0a5717f6da48d0",
        21708,
    ),
    "NWP-V.pickle.gz": (
        "b6c5fff860411fd8bd0e867f017cb30dfebbe43383a5d40856dea7273b3b61e4",
        21779,
    ),
    "RKSJ-H.pickle.gz": (
        "04eebe180a76d4cbf9bb30766f3f6e6a34bd405e9f3d2489a4a224b6ea8b4183",
        23030,
    ),
    "RKSJ-V.pickle.gz": (
        "e82162f5e17a530d30ba4286e8cfe5fd7b06c15bb24bd35c24fffb0c0bfe6fae",
        23048,
    ),
    "Roman-H.pickle.gz": (
        "c14560f556fddfb5ce63969202d0dadf945e1d299c83b4a2d0f63bc32b621ae5",
        394,
    ),
    "Roman-V.pickle.gz": (
        "9c384ecad95c1d84f8217fb6d45e691f2dd6d32868ea376e1cdab5b5cadd3473",
        394,
    ),
    "UniCNS-UCS2-H.pickle.gz": (
        "9bfcba21348cd2f285da716de8cb8caba8792eb7c0d9f9e2d58e188c6a4fc540",
        67459,
    ),
    "UniCNS-UCS2-V.pickle.gz": (
        "a2ff40a0f62dcb9fa0870b762a4ae3df9d17a5a934d647adcf60bc87b9b6a9ac",
        67395,
    ),
    "UniCNS-UTF16-H.pickle.gz": (
        "3d046fd093e6e1c2faacc55d76f7e10004e604dc5c0d563a72798af9880b178f",
        87819,
    ),
    "UniCNS-UTF16-V.pickle.gz": (
        "fbe9d89a138223615d0ab393a02b17a503e2e234a8e9459830918cc2b1ae3c95",
        87751,
    ),
    "UniCNS-UTF32-H.pickle.gz": (
        "deb724b20dbd952b6bd815f5c34c49ea09213699051abf6763616e67efc38cc1",
        87400,
    ),
    "UniCNS-UTF32-V.pickle.gz": (
        "771a07682b349a6e3bf7940ea76f167fce13f8d48e843e2ef56c83c36563bc13",
        87327,
    ),
    "UniCNS-UTF8-H.pickle.gz": (
        "a23c0066b14500c5fd93d6a96fcf4d00757766caf710532f8c272c6064be5ab3",
        82631,
    ),
    "UniCNS-UTF8-V.pickle.gz": (
        "cb8aa3e0f692167dd234aab1c598997d822533f3aea0e61474d466c71c100ad5",
        82562,
    ),
    "UniGB-UCS2-H.pickle.gz": (
        "0e33a654702dd5648e88e108f69cebf93995f31dbebfc17d92adc1e85949dd99",
        97445,
    ),
    "UniGB-UCS2-V.pickle.gz": (
        "a68b1f20918f68c3f122da4ed1f6b1dc26e4e71d0c5665c8501d82e4928ad956",
        97441,
    ),
    "UniGB-UTF16-H.pickle.gz": (
        "2d896f38caffb620c3b649c481e2296ad7863cb5352cf9c5b050476bb95c408f",
        101459,
    ),
    "UniGB-UTF16-V.pickle.gz": (
        "233a16fc3fa5b9cb68dc878fa7fef4fb75ecf29ddedd26e6c4030c098ac150ad",
        101331,
    ),
    "UniGB-UTF32-H.pickle.gz": (
        "2bfd4d0fd838ccb6e061733d14bb6bcdcfc6785f9eebbd1aa1b44b26751e5629",
        101490,
    ),
    "UniGB-UTF32-V.pickle.gz": (
        "fd299c9335fc05622b5f4b81ebbd003a4c4e610a14423b64a97447c5ab02ae2c",
        101357,
    ),
    "UniGB-UTF8-H.pickle.gz": (
        "115e481de49dd6e1f28c883f8e6f84c8b44d2c41b4e34ce945d344537e05e36d",
        90500,
    ),
    "UniGB-UTF8-V.pickle.gz": (
        "6a494d40f5c4696ebc4711337a5c9c75a29c5709a1bce273e74bcb96e60eafb8",
        90368,
    ),
    "UniJIS-UCS2-H.pickle.gz": (
        "690f47bb8b1088a90eb725aaec46d0ae4e49514d34631b39781b4e02092da10b",
        35934,
    ),
    "UniJIS-UCS2-HW-H.pickle.gz": (
        "a99b50e9af8664f1355a9c11e854a0688572c60ceda7c98a59bd41f186023484",
        412,
    ),
    "UniJIS-UCS2-HW-V.pickle.gz": (
        "267cffbeb41b759d691dce7e9358d1a044be8d13c1b3a6f18a9f2f134751a12d",
        1402,
    ),
    "UniJIS-UCS2-V.pickle.gz": (
        "fea3900be9885098c8f0ecffd6364b0ca74925d47e8ab8e2e0b403b01983afe8",
        35852,
    ),
    "UniJIS-UTF16-H.pickle.gz": (
        "082896892df1150bd18a57e2322279dcfa03b5feabb2363b55617ba6a4d96004",
        58054,
    ),
    "UniJIS-UTF16-V.pickle.gz": (
        "befaa6c0e17d9bc3319e3c57b10208b19dd9dbadc4b426eb7edb7004e5bf5a4e",
        57928,
    ),
    "UniJIS-UTF32-H.pickle.gz": (
        "7f101cb6b0ae66721a3092ad23f324b29d9c4e05ce114b7a2825facd807eb9cd",
        57910,
    ),
    "UniJIS-UTF32-V.pickle.gz": (
        "6ea53885e8ecea681bf391555474ad88351bcb84c75bb3259ddf83f46830b840",
        57780,
    ),
    "UniJIS-UTF8-H.pickle.gz": (
        "ab8d525e876ea6422a73ecb30c0d545e9356df96ac6a4d915954f8c0b0d38050",
        54764,
    ),
    "UniJIS-UTF8-V.pickle.gz": (
        "56aa1dafdd67a1989dc060b3ff29f1f671e8d12a5027545cd0467ba52b093b2a",
        54684,
    ),
    "UniJIS2004-UTF16-H.pickle.gz": (
        "5a04fdfd8ebba642fdc5a55cd11c415a875676e2a6916079824b7ce94addf189",
        58081,
    ),
    "UniJIS2004-UTF16-V.pickle.gz": (
        "88c5045b22659f6e0d7668c6c06b9a3092ef81e019a65c990dda5af40b6e476e",
        57960,
    ),
    "UniJIS2004-UTF32-H.pickle.gz": (
        "810e1c4181a525a24e8f1579bf634b8cbf7c5ced3d95807f62730a3acd51d3de",
        57940,
    ),
    "UniJIS2004-UTF32-V.pickle.gz": (
        "2dd4e1cead3842c72f812e5c1bdb52a1c3fcbbbc8eef0be40442d704ba8b29af",
        57811,
    ),
    "UniJIS2004-UTF8-H.pickle.gz": (
        "fdaa8d7268922da4ada59953bda61f68cd57db0514f8fffdcda4061da5afb0bc",
        54829,
    ),
    "UniJIS2004-UTF8-V.pickle.gz": (
        "2325aac634a5eb34e7b0658688eeb9bd3eec6376847cdb2d960776a17988aae9",
        54749,
    ),
    "UniJISX0213-UTF32-H.pickle.gz": (
        "5c05c04521e3825be9ca57a9b146276ef1798fde28efa774d6c6bdc66114918c",
        57903,
    ),
    "UniJISX0213-UTF32-V.pickle.gz": (
        "8c5ecec5f93f2d787e8dcd87982b1d69cbd01260a5233119a62753100a417c66",
        57778,
    ),
    "UniJISX02132004-UTF32-H.pickle.gz": (
        "a9015d0f18abed4b7116c6f40a0b3cbd656fa3368a7ae0418cddb2ca8eaf8d30",
        57930,
    ),
    "UniJISX02132004-UTF32-V.pickle.gz": (
        "f3e27416c17ad70e5baf8c9689232416ff9a97e00281ecda65fa095c5d444351",
        57808,
    ),
    "UniKS-UCS2-H.pickle.gz": (
        "25b2f6225f6578a6efa887abc7c9692c0d10b0f7e80cfdf3b2fc0a3b2436eef1",
        60683,
    ),
    "UniKS-UCS2-V.pickle.gz": (
        "84e14f40840c8f0f568503ea73ef9d6db710e70fa72615d1fda409697c683cbd",
        60699,
    ),
    "UniKS-UTF16-H.pickle.gz": (
        "e48c092ea05b663d4450a1568a6d28963e3009609748a6fac225d00aaa8e338f",
        61278,
    ),
    "UniKS-UTF16-V.pickle.gz": (
        "522c012d97ad399f9e886d50269458f04dd880140898f318ad0824a09679a023",
        61298,
    ),
    "UniKS-UTF32-H.pickle.gz": (
        "2a9ad44f1b07e802d6275320f6bcb948f74738114c0649d0e45e243c4196421f",
        61286,
    ),
    "UniKS-UTF32-V.pickle.gz": (
        "8f67bdc3b7983f570d7cdfdbf8969f09673ee077a1a3ff0575764adc6d4a0575",
        61309,
    ),
    "UniKS-UTF8-H.pickle.gz": (
        "986e8ad693f4f6ad16180908f5c019a17ccbd83a77fd432de34ac8e49d6f5a45",
        54151,
    ),
    "UniKS-UTF8-V.pickle.gz": (
        "ddb8953b9135dd43bf7fb4f7b30d71769870c1a3a2d9915e42da1a2150807357",
        54172,
    ),
    "V.pickle.gz": (
        "97a9c3f8c875fb8a5a5951f469f425a902237314cea487a88e2943fb383cc4c4",
        19826,
    ),
    "WP-Symbol-H.pickle.gz": (
        "452d3f14d51578b90a0475949f028751be09b6c0f781e0c0f3259c97b3cf9946",
        505,
    ),
    "WP-Symbol-V.pickle.gz": (
        "060fde272d9aeb6b28a190675e5a42db2c3f1f58695ae00eeeced415903d9bc4",
        505,
    ),
    "to-unicode-Adobe-CNS1.pickle.gz": (
        "089f95c2fa56447e68bb0b5619bb492b491198fd2ec5ea6cace097694142de68",
        138237,
    ),
    "to-unicode-Adobe-GB1.pickle.gz": (
        "06b3f8be1fab4fb8e5dd48d330337fd4c31292729b0a244137982d2521e4d30d",
        204425,
    ),
    "to-unicode-Adobe-Japan1.pickle.gz": (
        "de4e3d1dbe4e220f6406f31270af731b7650e8db2a5631018e6efd092384d053",
        112987,
    ),
    "to-unicode-Adobe-Korea1.pickle.gz": (
        "1d728c8f6a2cfa3644fe3658d2847781001efef47c8feb75ead4ff3f021f309e",
        120859,
    ),
}
