[package]
name = "syncpdf-font"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
syncpdf-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
skrifa = { workspace = true }
harfrust = { workspace = true }
subsetter = { workspace = true }
fontdb = { workspace = true }
unicode-bidi = { workspace = true }
unicode-script = { workspace = true }
tracing = { workspace = true }
pdf-writer = { workspace = true }
read-fonts = "0.44"

[dev-dependencies]
tempfile = { workspace = true }
lopdf = { workspace = true }
