from __future__ import annotations

from typing import Protocol


class PdfFontLike(Protocol):
    fontname: str | bytes

    def decode(self, data: bytes) -> object: ...

    def unicode_text(self, cid: int, fallback_text: str) -> str: ...

    def is_multibyte(self) -> bool: ...

    def is_vertical(self) -> bool: ...

    def char_width(self, cid: int) -> float: ...

    def char_disp(self, cid: int) -> float | tuple[float | None, float]: ...

    def get_descent(self) -> float: ...


class PdfRuntimeFontLike(PdfFontLike, Protocol):
    descent: float

    def runtime_identity(self) -> int: ...

    def compute_encoding_length(self, *, mupdf: object, xref_id: int) -> int: ...
